import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
import Topbar from '@/components/topbar'
const inter = Inter({ subsets: ['latin'] })
import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <div className='h-[100vh] bg-white'>
        <Providers>
          <Topbar />
          {children}
          </Providers>
        </div>
      </body>
    </html>
  )
}
